# Generated by Django 4.2.30 on 2026-09-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('city', models.CharField(max_length=120, verbose_name='ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='dirección')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='apellido')),
                ('billing_address', models.CharField(blank=True, max_length=240, verbose_name='dirección de facturación')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Retiro en sucursal'), ('delivery', 'Despacho a domicilio')], max_length=20, verbose_name='modalidad')),
                ('distance_km', models.PositiveIntegerField(default=0, verbose_name='distancia en km')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='costo de envío')),
                ('payment_method', models.CharField(choices=[('debit', 'Tarjeta de débito'), ('credit', 'Tarjeta de crédito'), ('transfer', 'Transferencia bancaria')], max_length=20, verbose_name='medio de pago')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music_pro.branch', verbose_name='sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('category', models.CharField(max_length=80, verbose_name='categoría')),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.PositiveIntegerField(verbose_name='precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('icon', models.CharField(default='music_note', max_length=40, verbose_name='ícono')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='cantidad')),
                ('unit_price', models.PositiveIntegerField(verbose_name='precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='music_pro.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music_pro.product')),
            ],
        ),
    ]
