# Generated by Django 4.2.30 on 2026-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_pro', '0004_remove_duplicate_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commune',
            field=models.CharField(blank=True, max_length=120, verbose_name='comuna'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, verbose_name='comentario para el repartidor'),
        ),
        migrations.AddField(
            model_name='order',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='tipo de vivienda'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='región'),
        ),
        migrations.AddField(
            model_name='order',
            name='rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
    ]
